# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-07 22:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0003_django18_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='submittedthing_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='full_place', serialize=False, to='sa_api_v2.SubmittedThing'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submittedthing_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='full_submission', serialize=False, to='sa_api_v2.SubmittedThing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
