# Generated by Django 4.2.9 on 2026-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0006_alter_submittedthing_visible_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='apikey',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='group',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='origin',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='origin',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
