# Generated by Django 4.2.9 on 2026-08-21 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sa_api_v2', '0007_apikey_display_name_apikey_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousValues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_name', models.TextField(db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_values', to='sa_api_v2.dataset')),
            ],
            options={
                'db_table': 'sa_api_anonymousvalues',
            },
        ),
    ]
