# Generated by Django 4.2.9 on 2024-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_social_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oauth2provider",
            options={"verbose_name": "OAuth2 Provider"},
        ),
        migrations.AddField(
            model_name="oauth2provider",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="\n        Describes the provider for documentation purposes. This field has no\n        impact on the behavior of the provider.\n    ",
            ),
        ),
        migrations.AlterField(
            model_name="oauth2provider",
            name="scope_separator",
            field=models.CharField(
                blank=True,
                default=" ",
                help_text="\n        The scope argument is usually a list of permissions to request, the\n        list is joined with a separator, usually just a blank space, but this\n        can differ from provider to provider. Override the default value with\n        this attribute if it differs.\n    ",
                max_length=10,
            ),
        ),
    ]
