# Generated by Django 4.2.9 on 2024-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_social_auth", "0004_oauth2provider_fullname_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2provider",
            name="use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="\n        If true, will include the client_id and client_secret as the\n        username/password when requesting the authorization token for a user.\n    ",
            ),
        ),
    ]
