# Generated by Django 4.2.9 on 2024-02-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_social_auth", "0005_oauth2provider_use_basic_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2provider",
            name="default_scope",
            field=models.TextField(
                blank=True,
                default="",
                help_text="\n        Some providers give nothing about the user but some basic data like the\n        user Id or an email address. The default scope attribute is used to\n        specify a default value for the scope argument to request those extra\n        bits. Should be a string using the `scope_separator` to distinguish\n        between scopes.\n    ",
            ),
        ),
    ]
